FROM php:8.3-fpm

WORKDIR /var/www/symfony

RUN apt-get update && apt-get install -y \
    git unzip libzip-dev zip libicu-dev libxml2-dev \
    libonig-dev curl \
    && docker-php-ext-install pdo pdo_mysql intl zip mbstring

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

CMD ["php-fpm"]
